const fs = require('fs').promises;
const os = require('os');
const path = require('path');

const CLI_WRAPPER_MARKER = '# Generated by Signboard CLI installer';
const PROFILE_BLOCK_START = '# >>> Signboard CLI >>>';
const PROFILE_BLOCK_END = '# <<< Signboard CLI <<<';
const UNIX_TARGET_DIR_SEGMENTS = ['.local', 'bin'];

function shellQuote(value) {
  return `'${String(value || '').replace(/'/g, `'\"'\"'`)}'`;
}

function getShellName(shellPath, platform = process.platform) {
  const normalized = String(shellPath || '').trim();
  if (normalized) {
    return path.basename(normalized).toLowerCase();
  }

  if (platform === 'darwin') {
    return 'zsh';
  }

  return 'sh';
}

function renderUnixWrapper({ executablePath, appPath, isPackaged }) {
  const commandParts = [shellQuote(executablePath)];

  if (!isPackaged) {
    commandParts.push(shellQuote(appPath));
  }

  commandParts.push('"$@"');

  return [
    '#!/bin/sh',
    CLI_WRAPPER_MARKER,
    `exec ${commandParts.join(' ')}`,
    '',
  ].join('\n');
}

function renderPosixProfileBlock(relativeTargetDir) {
  return [
    PROFILE_BLOCK_START,
    `export PATH="$HOME/${relativeTargetDir}:$PATH"`,
    PROFILE_BLOCK_END,
    '',
  ].join('\n');
}

function renderFishProfileBlock(relativeTargetDir) {
  return [
    PROFILE_BLOCK_START,
    `if not contains "$HOME/${relativeTargetDir}" $PATH`,
    `    fish_add_path "$HOME/${relativeTargetDir}"`,
    'end',
    PROFILE_BLOCK_END,
    '',
  ].join('\n');
}

function buildProfilePlan({ homeDir, shellName, platform }) {
  const relativeTargetDir = UNIX_TARGET_DIR_SEGMENTS.join('/');
  const targetDir = path.join(homeDir, ...UNIX_TARGET_DIR_SEGMENTS);

  if (shellName === 'fish') {
    return {
      targetDir,
      relativeTargetDir,
      profiles: [
        {
          path: path.join(homeDir, '.config', 'fish', 'config.fish'),
          block: renderFishProfileBlock(relativeTargetDir),
        },
      ],
    };
  }

  if (shellName === 'zsh') {
    return {
      targetDir,
      relativeTargetDir,
      profiles: [
        {
          path: path.join(homeDir, '.zprofile'),
          block: renderPosixProfileBlock(relativeTargetDir),
        },
      ],
    };
  }

  if (shellName === 'bash') {
    return {
      targetDir,
      relativeTargetDir,
      profiles: [
        {
          path: path.join(homeDir, platform === 'darwin' ? '.bash_profile' : '.profile'),
          block: renderPosixProfileBlock(relativeTargetDir),
        },
      ],
    };
  }

  return {
    targetDir,
    relativeTargetDir,
    profiles: [
      {
        path: path.join(homeDir, '.profile'),
        block: renderPosixProfileBlock(relativeTargetDir),
      },
    ],
  };
}

function upsertProfileBlock(existingContent, block) {
  const source = String(existingContent || '');
  const startIndex = source.indexOf(PROFILE_BLOCK_START);
  const endIndex = source.indexOf(PROFILE_BLOCK_END);

  if (startIndex >= 0 && endIndex >= startIndex) {
    const before = source.slice(0, startIndex).replace(/\s*$/, '\n');
    const after = source.slice(endIndex + PROFILE_BLOCK_END.length).replace(/^\s*/, '\n');
    return `${before}${block}${after}`.replace(/\n{3,}/g, '\n\n');
  }

  if (!source.trim()) {
    return block;
  }

  const normalized = source.endsWith('\n') ? source : `${source}\n`;
  return `${normalized}\n${block}`.replace(/\n{3,}/g, '\n\n');
}

async function writeProfileBlock(profilePath, block) {
  let existing = '';

  try {
    existing = await fs.readFile(profilePath, 'utf8');
  } catch (error) {
    if (!error || error.code !== 'ENOENT') {
      throw error;
    }
  }

  const nextContent = upsertProfileBlock(existing, block);
  const changed = nextContent !== existing;

  if (changed) {
    await fs.mkdir(path.dirname(profilePath), { recursive: true });
    await fs.writeFile(profilePath, nextContent, 'utf8');
  }

  return changed;
}

async function writeWrapperScript(scriptPath, content) {
  let existing = '';

  try {
    existing = await fs.readFile(scriptPath, 'utf8');
  } catch (error) {
    if (!error || error.code !== 'ENOENT') {
      throw error;
    }
  }

  if (existing && !existing.includes(CLI_WRAPPER_MARKER)) {
    throw new Error(`Refusing to overwrite existing command at ${scriptPath}`);
  }

  if (existing !== content) {
    await fs.writeFile(scriptPath, content, 'utf8');
  }

  await fs.chmod(scriptPath, 0o755);
}

async function installCliForCurrentUser({
  executablePath,
  appPath,
  isPackaged,
  platform = process.platform,
  shellPath = process.env.SHELL,
  homeDir = os.homedir(),
} = {}) {
  if (!['darwin', 'linux'].includes(platform)) {
    throw new Error('CLI installation from the app is currently supported on macOS and Linux only.');
  }

  const resolvedExecutablePath = path.resolve(String(executablePath || process.execPath));
  const resolvedAppPath = path.resolve(String(appPath || process.cwd()));
  const resolvedHomeDir = path.resolve(String(homeDir || os.homedir()));
  const shellName = getShellName(shellPath, platform);
  const profilePlan = buildProfilePlan({
    homeDir: resolvedHomeDir,
    shellName,
    platform,
  });
  const scriptPath = path.join(profilePlan.targetDir, 'signboard');
  const scriptContent = renderUnixWrapper({
    executablePath: resolvedExecutablePath,
    appPath: resolvedAppPath,
    isPackaged: isPackaged !== false,
  });

  await fs.mkdir(profilePlan.targetDir, { recursive: true });
  await writeWrapperScript(scriptPath, scriptContent);

  const updatedProfiles = [];
  const untouchedProfiles = [];

  for (const profile of profilePlan.profiles) {
    const changed = await writeProfileBlock(profile.path, profile.block);
    if (changed) {
      updatedProfiles.push(profile.path);
    } else {
      untouchedProfiles.push(profile.path);
    }
  }

  return {
    commandName: 'signboard',
    scriptPath,
    targetDir: profilePlan.targetDir,
    shellName,
    updatedProfiles,
    untouchedProfiles,
    commandPreview: 'signboard help',
  };
}

module.exports = {
  CLI_WRAPPER_MARKER,
  PROFILE_BLOCK_START,
  PROFILE_BLOCK_END,
  getShellName,
  renderUnixWrapper,
  installCliForCurrentUser,
};
